// Generated by CoffeeScript 1.6.3
(function() {
  var PORT, app, server;

  PORT = require("./config.json").port;

  app = require("./app");

  server = app.listen(PORT);

  console.log("Listening on port " + PORT);

}).call(this);
